select * from customer limit 20

--Q1 WHAT IS THE TOTAL REVAENUE GENERATED BY MALE VS . FAMALE CUSTOMERS/
SELECT gender, SUM(purchase_amount) as revanue
from customer 
group by gender 


--Q2, which customers used a discount but still spent more then avarege purchase amount ?
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >=  (select AVG(purchase_amount) from customer)


--Q3. which are the top 8 product with the highest average review rating

select item_purchased , ROUND(AVG(review_rating::numeric),2) as "average product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 8;


--Q4, compare the average purchase amounts between standerd and express shipping.
select shipping_type,
ROUND(AVG(purchase_amount) ,2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subsribed customerS spend more? compare avarage spend and total revenue betwwwen sabcribers and non subcribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status 
order by total_revenue , avg_spend desc;

--Q6 which 5 products have the highest percentage of purchase with discount applies?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
group by item_purchased 
order by discount_rate desc
limit 8;

--segment customers into new , raturning, and loyal based on their total number of privious purchase, and show 
--count of each segment,

WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT 
    customer_segment, 
    COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;

--Q8 what are the top 3 mosst purchased prosuct within each catgoty?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


--Q9 are customers who are repeat buyers (more then 3 previous purchases ) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >3
group by subscription_status

--Q10 what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue 
from customer
group by age_group
order by total_revenue desc;
